### ISSUE TITLE
Version 1.1.0

### ISSUE THREAD

**Issue by onevcat** [swifter-tips/Public-Issues#12]
- [x] https://github.com/swifter-tips/Public-Issues/issues/11 《属性访问控制》中“Swift 中的 `swift` 和其他大部分语言不太一样” 应为 “Swift 中的 `private` 和其他大部分语言不太一样”
- [x] https://github.com/swifter-tips/Public-Issues/issues/10 《代码组织和 Framework》中 “开发中我们所使以的第三方框” 改为 “开发中我们所使用的第三方框”
- [x] https://github.com/swifter-tips/Public-Issues/issues/13 《方法名称参数省略》中 “使用自动覆盖的方式” 应为 “使用原子写入的方式”
- [x] https://github.com/swifter-tips/Public-Issues/issues/14 《内存管理，weak 和 unowned》中对 unowed 的表述不当，进行了修正
- [x] https://github.com/swifter-tips/Public-Issues/issues/15 《字面量转换》的内容完全重写，更新为适应 Swift 1.1 版本。
- [x] `Any` 现在可以支持方法类型了，因此对《Any 和 AnyObject》一节作出修正。
- [x] 在本书 1.0.1 版本的基础上，进一步修正了《初始化返回 nil》一节的内容，使其更适应 Swift 1.1 关于可失败的初始化方法的修正。

**Comment by onevcat** [comment]
更新完成。
