### ISSUE TITLE
Version 1.0.1

### ISSUE THREAD

**Issue by onevcat** [swifter-tips/Public-Issues#4]
1.0.1 对书中错误进行小幅修正
- [x] https://github.com/swifter-tips/Public-Issues/issues/2 《将 protocol 的方法声明为 mutating》中 `blueColor()!` -> `blueColor()`。`blueColor()` 返回的已经是 `UIColor` 而不是 `UIColor?` 
- [x] https://github.com/swifter-tips/Public-Issues/issues/5 《typealias 和泛型接口》中有误字 “wei”，删除
- [x] https://github.com/swifter-tips/Public-Issues/issues/6 《Optional Chaining 文字错误》 `它们的等价的` -> `它们是等价的`
- [x] https://github.com/swifter-tips/Public-Issues/issues/7 《Swift 命令行工具》中示例代码 `xcrun swift MyClass.swift main.swift` 应当为 `xcrun swiftc MyClass.swift main.swift`
- [x] https://github.com/swifter-tips/Public-Issues/issues/8 《多类型和容器》中在 `let mixed: [Printable]` 上面添加 `import Foundation`，因为 `String` 并没有实现 `Printable`，这里被强转为了 `Selector`。这个例子不是太好，重写。
- [x] https://github.com/swifter-tips/Public-Issues/issues/9 《内存管理，weak 和 unowned》中 “变量一定需要时 Optional值 ” -> "变量一定需要是Optional值"

**Comment by onevcat** [comment]
Version 1.0.1 发布。
